[package]
name = "astroport-generator"
version = "2.3.2"
authors = ["Astroport"]
edition = "2021"

exclude = [
    # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
    "contract.wasm",
    "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw-storage-plus = "0.15"
cw1-whitelist = { version = "0.15", features = ["library"] }
thiserror = { version = "1.0" }
astroport-governance = { git = "https://github.com/astroport-fi/astroport-governance", version = "1" }
protobuf = { version = "2", features = ["with-bytes"] }
cosmwasm-std = "1.1"
cw2 = "0.15"
cw20 = "0.15"
astroport = { path = "../../../packages/astroport", version = "3" }
cosmwasm-schema = "1.1"
cw-utils = "1.0.1"

[dev-dependencies]
generator-controller = { git = "https://github.com/astroport-fi/astroport-governance" }
astroport-mocks = { path = "../../../packages/astroport_mocks" }
astroport-token = { path = "../../token" }
astroport-vesting = { path = "../vesting" }
astroport-staking = { path = "../staking" }
astroport-factory = { path = "../../factory" }
astroport-pair = { path = "../../pair" }
astroport-pair-stable = { path = "../../pair_stable" }
astroport-whitelist = { path = "../../whitelist" }
anyhow = "1"
voting-escrow = { git = "https://github.com/astroport-fi/astroport-governance" }
voting-escrow-delegation = { git = "https://github.com/astroport-fi/astroport-governance" }
astroport-nft = { git = "https://github.com/astroport-fi/astroport-governance" }
cw721-base = { version = "0.15", features = ["library"] }
generator-proxy-to-vkr = { git = "https://github.com/astroport-fi/astro-generator-proxy-contracts", branch = "main" }
valkyrie = { git = "https://github.com/astroport-fi/valkyrieprotocol", rev = "b5fcb666f17d7e291f40365756e50fc0d7b9bf54" }
valkyrie-lp-staking = { git = "https://github.com/astroport-fi/valkyrieprotocol", rev = "b5fcb666f17d7e291f40365756e50fc0d7b9bf54" }
valkyrie-vp = { git = "https://github.com/astroport-fi/valkyrieprotocol", rev = "b5fcb666f17d7e291f40365756e50fc0d7b9bf54" }
astroport-native-coin-registry = { path = "../../periphery/native_coin_registry" }
